import React,{Component,Suspense,lazy,useCallback,useEffect,useMemo,useState} from 'react';
import {COLUMNS,DEPARTMENTS,METRICS,enrichRows,filterRows,geographyIndex,monthLabel,normalizeGeography,number,percent,readDataset,selectGeoJSON,summarize,toCSV} from './data.js';
import Trend from './Trend.jsx';
import {PALETTES} from './kepler-config.js';

const KeplerMap=lazy(()=>import('./KeplerMap.jsx'));
class MapBoundary extends Component{
  state={failed:false};static getDerivedStateFromError(){return {failed:true};}
  render(){return this.state.failed?<div className="map-empty"><strong>No fue posible iniciar el mapa.</strong><p>La tabla y los gráficos siguen disponibles. Comprueba WebGL y la aceleración gráfica del navegador.</p></div>:this.props.children;}
}
function Download({rows,label='Descargar selección'}){
  function download(){const url=URL.createObjectURL(new Blob([toCSV(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='seleccion_dashboard.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <button className="button secondary" disabled={!rows.length} onClick={download}>{label} <span aria-hidden="true">↓</span></button>;
}
const fixed=(v,digits)=>Number.isFinite(v)?new Intl.NumberFormat('es-CO',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(v):'—';
function Score({value,label,help,digits=3,percentage=false}){return <article className="score"><p>{label}</p><strong>{Number.isFinite(value)?percentage?percent(value):fixed(value,digits):'—'}</strong><small>{help}</small></article>;}
function Stress({title,period,values}){
  if(!values)return null;
  return <article className="stress-card"><p className="eyebrow">{title}</p><strong>AUC {fixed(values.auc,4)}</strong><dl><div><dt>RMSE log</dt><dd>{fixed(values.rmse_log,3)}</dd></div><div><dt>Winkler log</dt><dd>{fixed(values.winkler_log,3)}</dd></div><div><dt>Cobertura</dt><dd>{percent(values.coverage_80)}</dd></div></dl><small>{period}</small></article>;
}

export default function App(){
  const [dataset,setDataset]=useState(null),[geography,setGeography]=useState(null),[geoLabel,setGeoLabel]=useState('Sin cartografía');
  const [view,setView]=useState('explorer'),[month,setMonth]=useState(''),[department,setDepartment]=useState(''),[query,setQuery]=useState(''),[metric,setMetric]=useState('prob_evento'),[threshold,setThreshold]=useState(.5),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState(0);
  const index=useMemo(()=>geographyIndex(geography),[geography]);
  const all=useMemo(()=>enrichRows(dataset?.rows??[],index),[dataset,index]);
  const months=useMemo(()=>[...new Set(all.map(r=>r.fecha))].sort(),[all]);
  const filtered=useMemo(()=>filterRows(all,{month,department,query}),[all,month,department,query]);
  const ordered=useMemo(()=>[...filtered].sort((a,b)=>b[metric]-a[metric]||a.DIVIPOLA.localeCompare(b.DIVIPOLA)),[filtered,metric]);
  const summary=useMemo(()=>summarize(filtered,threshold),[filtered,threshold]);
  const mapped=useMemo(()=>selectGeoJSON(filtered,index),[filtered,index]);
  const maxValue=useMemo(()=>metric==='prob_evento'?1:all.reduce((max,r)=>Math.max(max,r[metric]),0),[all,metric]);
  const series=useMemo(()=>all.filter(r=>r.DIVIPOLA===selected),[all,selected]);
  const current=series.find(r=>r.fecha===month), stats=dataset?.metadata?.metrics, folds=dataset?.metadata?.protocol?.folds??[];
  const availableDepartments=useMemo(()=>[...new Set(all.map(r=>r.departamento_codigo))].sort(),[all]);
  const selectedLabel=series[0]?.municipio??selected;
  const setSelection=useCallback(code=>setSelected(code),[]);
  useEffect(()=>{setPage(0);},[month,department,query,metric]);
  useEffect(()=>{if(!filtered.some(r=>r.DIVIPOLA===selected))setSelected(ordered[0]?.DIVIPOLA??'');},[filtered,ordered,selected]);
  const applyDataset=useCallback(data=>{
    setDataset(data);setGeography(data.geography??null);setGeoLabel(data.geography?data.metadata?.geography_source??'Cartografía incluida':'Sin cartografía');
    setMonth([...new Set(data.rows.map(r=>r.fecha))].sort()[0]);setDepartment('');setQuery('');setSelected('');setError('');
  },[]);
  useEffect(()=>{
    let active=true;
    // El exportador genera este archivo; el scaffold no contiene predicciones oficiales.
    fetch('./datos.json',{cache:'no-store'}).then(r=>r.ok?r.text():null).then(t=>{if(t&&active)applyDataset(readDataset(t,'datos.json'));}).catch(e=>{if(active)setError(`No se pudo cargar datos.json: ${e.message}`);});
    return()=>{active=false;};
  },[applyDataset]);
  async function loadFile(event,geo=false){
    const file=event.target.files[0];event.target.value='';if(!file)return;
    setBusy(true);setError('');
    try{
      if(file.size>30*1024*1024)throw new Error('Archivo mayor de 30 MB. Simplifica la cartografía o usa el exportador Python.');
      const text=await file.text();
      if(geo){setGeography(normalizeGeography(JSON.parse(text)));setGeoLabel(file.name);}
      else applyDataset(readDataset(text,file.name));
    }catch(e){setError(e.message);}finally{setBusy(false);}
  }
  const mode=dataset?.synthetic===true?'Ensayo · datos inventados':dataset?.synthetic===false?'Resultados del run · uso interno':dataset?'CSV cargado · procedencia sin verificar':'Sin resultados cargados';
  const nav=[['explorer','Explorar territorio','01'],['validation','Validación del modelo','02'],['sources','Fuentes y metodología','03']];
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#main"><span className="brand-mark" aria-hidden="true">T</span><span>TECTON<small>INTELIGENCIA TERRITORIAL</small></span></a>
      <p className="nav-title">HACKATHON · PNUD COLOMBIA</p><nav aria-label="Vistas del dashboard">{nav.map(([id,label,n])=><button key={id} aria-current={view===id?'page':undefined} className={view===id?'active':''} onClick={()=>setView(id)}><span>{n}</span>{label}</button>)}</nav>
      <div className="sidebar-note"><span className="status-dot"/>Entorno local<p>Riesgo, magnitud e incertidumbre a escala municipal.</p><small>Predicciones mensuales · no alertas oficiales</small></div>
    </aside>
    <main id="main"><header className="page-header"><div><p className="eyebrow">{view==='explorer'?'GEOVISOR / EXPLORACIÓN':view==='validation'?'MODELO / EVIDENCIA':'DATOS / TRAZABILIDAD'}</p><h1>{view==='explorer'?'Riesgo territorial':view==='validation'?'Validación temporal':'Fuentes y metodología'}</h1><p className="subtitle">{view==='explorer'?'Explora dónde se concentra el riesgo y qué tan amplia es la incertidumbre.':view==='validation'?'Evidencia calculada antes del período de prueba.':'Definiciones, cobertura y procedencia de los resultados.'}</p></div>
      <div className="file-actions"><label className="button primary">Cargar resultados<input disabled={busy} type="file" accept=".csv,.json" onChange={e=>loadFile(e)}/></label><label className="button secondary">Cargar cartografía<input disabled={busy} type="file" accept=".json,.geojson" onChange={e=>loadFile(e,true)}/></label></div></header>
      <div className={`source-strip ${dataset?.synthetic?'demo-strip':''}`}><span><span className="status-dot"/>{mode}</span><span>{dataset?`${number(all.length)} filas · ${months.length} meses`:'CSV de predicciones o JSON exportado desde Python'}{dataset?.metadata?.model_name?` · modelo ${dataset.metadata.model_name}`:''}</span></div>
      {error&&<div className="error" role="alert"><strong>No se aplicó la carga.</strong> {error}<button aria-label="Cerrar mensaje" onClick={()=>setError('')}>×</button></div>}
      {busy&&<p role="status" className="muted">Validando archivo…</p>}
      {!dataset&&<section className="welcome"><div className="welcome-icon" aria-hidden="true">↗</div><div><h2>Conecta los resultados del modelo</h2><p>Carga <code>predicciones.csv</code> o el <code>datos.json</code> del exportador. Después añade los polígonos municipales con DIVIPOLA. Los filtros y gráficos estarán disponibles al validar el archivo.</p><p className="muted">El visor abre sin datos oficiales. El archivo de ensayo incluido en el ZIP permite comprobar el flujo con valores inventados.</p></div></section>}
      {view==='explorer'&&<>
        <section className="filters" aria-label="Filtros globales"><label>Mes<select value={month} disabled={!dataset} onChange={e=>setMonth(e.target.value)}>{months.length?months.map(m=><option key={m} value={m}>{monthLabel(m)}</option>):<option>Sin datos</option>}</select></label><label>Departamento<select value={department} disabled={!dataset} onChange={e=>setDepartment(e.target.value)}><option value="">Todos los departamentos</option>{availableDepartments.map(d=><option key={d} value={d}>{DEPARTMENTS[d]??d}</option>)}</select></label><label className="search-label">Municipio o DIVIPOLA<input type="search" placeholder="Buscar por nombre o código…" value={query} disabled={!dataset} onChange={e=>setQuery(e.target.value)}/></label><label>Variable del mapa<select value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(METRICS).map(([key,m])=><option key={key} value={key}>{m.label}</option>)}</select></label></section>
        <section className="summary-strip" aria-label="Resumen de la selección"><Score value={dataset?summary.municipalities:null} label="Municipios en la selección" help={`${monthLabel(month)} · filtros vigentes`} digits={0}/><Score value={dataset?summary.above:null} label={`Probabilidad ≥ ${percent(threshold)}`} help="Umbral exploratorio, ajustable; sin categoría oficial" digits={0}/><Score value={dataset?summary.people:null} label="Suma de personas estimadas" help="Suma de puntos del modelo; no población observada" digits={0}/></section>
        <div className="explorer-grid"><section className="panel map-panel"><div className="panel-head"><div><p className="eyebrow">DISTRIBUCIÓN MUNICIPAL</p><h2>{METRICS[metric].label}</h2></div><span className="map-count">{mapped.features.length}/{filtered.length} con geometría</span></div>
          <div className="map-frame">{mapped.features.length?<MapBoundary key={`${dataset?.metadata?.run_id??'csv'}-${geography?.features.length}`}><Suspense fallback={<div className="map-empty" role="status">Iniciando Kepler.gl…</div>}><KeplerMap geojson={mapped} metric={metric} maxValue={maxValue} onSelect={setSelection}/></Suspense></MapBoundary>:<div className="map-empty"><span className="map-symbol" aria-hidden="true">⌖</span><h3>{!dataset?'Mapa listo para conectar':!geography?'Añade cartografía municipal':filtered.length?'No hay coincidencias geográficas':'No hay resultados para estos filtros'}</h3><p>{!geography?'Carga GeoJSON de DANE en WGS84 con el campo mpio_cdpmp o DIVIPOLA.':'Los municipios sin coincidencia permanecen en la tabla y en los totales.'}</p></div>}</div>
          <div className="map-footer"><div className="legend"><div className="legend-swatches">{PALETTES[metric].map(c=><span key={c} style={{background:c}}/>)}</div><div className="legend-labels"><span>0{metric==='prob_evento'?'%':''}</span><span>{metric==='prob_evento'?'50%':number(Math.expm1(Math.max(1,Math.log1p(maxValue))/2))}</span><span>{metric==='prob_evento'?'100%':number(Math.expm1(Math.max(1,Math.log1p(maxValue))))}</span></div><small>{metric==='prob_evento'?'Escala fija de 0 a 100%':'Color sobre log(1 + valor) · dominio fijo del archivo'}</small></div><p>{geoLabel==='Sin cartografía'?'Cartografía pendiente':geoLabel}<br/><small>Polígonos locales · sin servicios de mapas externos</small></p></div>
          {!!(filtered.length-mapped.features.length)&&<p className="coverage-note">{number(filtered.length-mapped.features.length)} municipios de la selección sin geometría. Se incluyen en las cifras.</p>}
        </section><section className="panel priority-panel"><div className="panel-head"><div><p className="eyebrow">ORDEN EXPLORATORIO</p><h2>Municipios destacados</h2></div></div><p className="muted small">Ordenados por {METRICS[metric].label.toLowerCase()}.</p>
          {ordered.length?<ol className="ranking">{ordered.slice(0,7).map((r,i)=><li key={r.DIVIPOLA}><button className={selected===r.DIVIPOLA?'selected':''} onClick={()=>setSelected(r.DIVIPOLA)}><span className="rank-number">{String(i+1).padStart(2,'0')}</span><span className="rank-name">{r.municipio}<small>{r.departamento} · {r.DIVIPOLA}</small></span><strong>{metric==='prob_evento'?percent(r[metric]):number(r[metric])}</strong><span className="rank-bar" style={{width:`${Math.max(3,Math.min(100,(metric==='prob_evento'?r[metric]:Math.log1p(r[metric])/Math.max(1,Math.log1p(maxValue)))*100))}%`}}/></button></li>)}</ol>:<p className="no-ranking">Sin municipios para mostrar.</p>}
          <div className="threshold"><label htmlFor="threshold">Umbral de probabilidad <strong>{percent(threshold)}</strong></label><input id="threshold" type="range" min="0" max="1" step=".05" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/><small>Solo cambia el conteo del resumen. No oculta municipios.</small></div>
        </section></div>
        <section className="panel detail-panel"><div className="panel-head"><div><p className="eyebrow">DETALLE DEL MUNICIPIO</p><h2>{selectedLabel||'Selecciona un municipio'}</h2><p className="muted small">{series[0]?.departamento??'Desde el mapa o la tabla'}{selected?` · DIVIPOLA ${selected}`:''}</p></div>{current&&<span className="detail-value">{percent(current.prob_evento)}<small>probabilidad en {monthLabel(month)}</small></span>}</div><div className="trend-grid"><Trend rows={series}/><Trend rows={series} probability/></div>{series.length>0&&<details><summary>Ver valores mensuales exactos</summary><div className="table-scroll"><table><thead><tr><th>Mes</th><th>Probabilidad</th><th>Personas estimadas</th><th>q10</th><th>q90</th></tr></thead><tbody>{series.map(r=><tr key={r.fecha}><td>{monthLabel(r.fecha)}</td><td>{percent(r.prob_evento)}</td><td>{number(r.personas_desplazadas_estimadas,2)}</td><td>{number(r.personas_desplazadas_q10,2)}</td><td>{number(r.personas_desplazadas_q90,2)}</td></tr>)}</tbody></table></div></details>}<p className="footnote">Detalle: todos los meses del municipio seleccionado. La banda q10–q90 es un intervalo predictivo nominal del 80%; su cobertura debe comprobarse en validación.</p></section>
        <section className="panel table-panel"><div className="panel-head"><div><p className="eyebrow">DATOS DE LA SELECCIÓN</p><h2>Resultados municipales</h2></div><Download rows={ordered}/></div><div className="table-scroll"><table><caption className="sr-only">Predicciones del mes y filtros seleccionados, ordenadas por {METRICS[metric].label}</caption><thead><tr><th>Municipio</th><th>Departamento</th><th>Probabilidad</th><th>Personas estimadas</th><th>q10–q90</th><th>Amplitud</th><th>Geometría</th></tr></thead><tbody>{ordered.slice(page*25,(page+1)*25).map(r=><tr key={r.DIVIPOLA} className={selected===r.DIVIPOLA?'selected-row':''}><td><button className="table-select" onClick={()=>setSelected(r.DIVIPOLA)}>{r.municipio}<small>{r.DIVIPOLA}</small></button></td><td>{r.departamento}</td><td><span className="probability-bar" style={{'--fill':`${r.prob_evento*100}%`}}/>{percent(r.prob_evento)}</td><td>{number(r.personas_desplazadas_estimadas,1)}</td><td>{number(r.personas_desplazadas_q10,1)}–{number(r.personas_desplazadas_q90,1)}</td><td>{number(r.amplitud,1)}</td><td>{index.has(r.DIVIPOLA)?'Disponible':'Pendiente'}</td></tr>)}</tbody></table>{!ordered.length&&<p className="empty-table">No hay filas que coincidan.</p>}</div><div className="pagination"><span>{ordered.length?`${number(page*25+1)}–${number(Math.min((page+1)*25,ordered.length))} de ${number(ordered.length)}`:'0 filas'}</span><div><button disabled={!page} onClick={()=>setPage(p=>p-1)}>← Anterior</button><button disabled={(page+1)*25>=ordered.length} onClick={()=>setPage(p=>p+1)}>Siguiente →</button></div></div><p className="footnote">La descarga contiene únicamente la selección visible en formato oficial de seis columnas; no sustituye el CSV completo de entrega.</p></section>
      </>}
      {view==='validation'&&<>
        {!stats&&<section className="welcome"><div><h2>Métricas pendientes</h2><p>El CSV de prueba no permite medir desempeño sin etiquetas. Exporta un run completo para incluir métricas de validación temporal y hashes.</p></div></section>}
        <section className="summary-strip validation-strip"><Score value={stats?.summary?.auc_mean} label="AUC medio" help="Mayor es mejor · media de folds temporales"/><Score value={stats?.summary?.rmse_log_mean} label="RMSE en log(1 + personas)" help="Menor es mejor · todas las filas de validación"/><Score value={stats?.summary?.winkler_log_mean} label="Winkler en escala log" help="Menor es mejor · intervalo nominal 80%"/><Score value={stats?.summary?.coverage_80_mean} label="Cobertura observada q10–q90" help="Objetivo nominal 80% · media de folds" percentage/></section>
        <section className="panel"><div className="panel-head"><div><p className="eyebrow">VALIDACIÓN ANTERIOR A PRUEBA</p><h2>Resultados por fold</h2></div></div><div className="table-scroll"><table><thead><tr><th>Fold</th><th>Entrena hasta</th><th>Valida</th><th>Filas</th><th>AUC</th><th>RMSE log</th><th>Winkler log</th><th>Cobertura</th></tr></thead><tbody>{(stats?.folds??[]).map(f=>{const p=folds[f.fold-1];return <tr key={f.fold}><td>{f.fold}</td><td>{p?monthLabel(p.train_end):'—'}</td><td>{p?`${monthLabel(p.valid_start)} – ${monthLabel(p.valid_end)}`:'—'}</td><td>{number(f.validation_rows)}</td><td>{fixed(f.auc,4)}</td><td>{fixed(f.rmse_log,3)}</td><td>{fixed(f.winkler_log,3)}</td><td>{percent(f.coverage_80)}</td></tr>;})}</tbody></table>{stats&&!stats.folds?.length&&<p className="empty-table">El run no registró folds.</p>}</div><p className="footnote">Cada fold entrena solo con meses anteriores a su validación; la historia de cada municipio queda congelada en el corte, como en la prueba.</p></section>
        {(stats?.stress_12_months||stats?.stress_far_13_24)&&<section className="panel"><div className="panel-head"><div><p className="eyebrow">PRUEBAS DE HORIZONTE</p><h2>Qué tan lejos se sostiene</h2></div></div><div className="stress-grid"><Stress title="1 A 12 MESES DEL CORTE" period="Entrena hasta sept 2021 · valida oct 2021 – sept 2022 (parecido a la prueba pública)" values={stats?.stress_12_months}/><Stress title="13 A 24 MESES DEL CORTE" period="Entrena hasta sept 2020 · valida oct 2021 – sept 2022 (más cerca de la prueba privada, a 20–39 meses)" values={stats?.stress_far_13_24}/></div><p className="footnote">Estas cifras describen el protocolo del run. No representan resultados del período de prueba ni una puntuación oficial de la hackathon.</p></section>}
      </>}
      {view==='sources'&&<div className="method-grid"><section className="panel prose"><p className="eyebrow">SIGNIFICADO DE LAS VARIABLES</p><h2>Cómo leer los resultados</h2><dl><dt>Probabilidad de evento</dt><dd>Probabilidad mensual de un evento con personas o viviendas afectadas. Puede existir evento con cero personas reportadas.</dd><dt>Personas estimadas</dt><dd>La columna oficial se llama personas_desplazadas_estimadas. Según el diccionario del reto, el target se construye con personas reportadas como afectadas.</dd><dt>q10 y q90</dt><dd>Cuantiles predictivos del modelo. Su amplitud indica incertidumbre de magnitud. No es una probabilidad adicional ni un intervalo de confianza.</dd><dt>Suma de personas estimadas</dt><dd>Suma de puntos predichos para el mes y filtros seleccionados. El ajuste en escala log no garantiza una media insesgada. No se suman cuantiles para construir un intervalo nacional.</dd><dt>Umbral exploratorio</dt><dd>Un conteo para explorar la selección. No constituye una categoría de emergencia ni una recomendación operativa validada.</dd></dl></section><section className="panel prose"><p className="eyebrow">PROCEDENCIA Y COBERTURA</p><h2>Archivo activo</h2><dl><dt>Fuente de predicciones</dt><dd>{dataset?.metadata?.source??'Sin archivo'}</dd><dt>Run</dt><dd className="mono">{dataset?.metadata?.run_id??'No verificable desde un CSV aislado'}</dd><dt>Modelo</dt><dd>{dataset?.metadata?.model_name??'Sin registro'}</dd><dt>Exportado</dt><dd>{dataset?.metadata?.generated_at?new Intl.DateTimeFormat('es-CO',{dateStyle:'long',timeStyle:'short'}).format(new Date(dataset.metadata.generated_at)):'Sin registro'}</dd><dt>SHA256 del CSV de predicciones</dt><dd className="mono hash">{dataset?.metadata?.predictions_sha256??'Pendiente: usar exportador Python'}</dd><dt>Cartografía</dt><dd>{geoLabel}<br/>Unión por DIVIPOLA; nombres desde GeoJSON. Municipios sin unión permanecen en las cifras.</dd><dt>Cobertura temporal</dt><dd>{months.length?`${monthLabel(months[0])} a ${monthLabel(months.at(-1))}`:'Sin resultados'}</dd><dt>Flujo local</dt><dd>Los archivos se leen en el navegador. El fondo cartográfico no consulta servicios externos. Las predicciones no se publican.</dd></dl></section>{!!dataset?.metadata?.model_sources?.length&&<section className="panel full-width"><div className="panel-head"><div><p className="eyebrow">DATOS QUE ALIMENTAN EL MODELO</p><h2>Fuentes declaradas</h2></div></div><div className="table-scroll"><table className="sources-table"><thead><tr><th>Fuente</th><th>Entidad</th><th>Uso en el modelo</th><th>Período</th></tr></thead><tbody>{dataset.metadata.model_sources.map(s=><tr key={s.fuente}><td>{s.fuente}</td><td>{s.entidad}</td><td>{s.uso}</td><td>{s.periodo}</td></tr>)}</tbody></table></div><p className="footnote">Fuentes colombianas desde 2018 y sin observaciones de los meses de prueba. Citas completas en docs/fuentes_datos.csv.</p></section>}
        <section className="panel prose full-width"><p className="eyebrow">TRANSFERENCIA Y ENTREGA</p><h2>Un mismo motor de Python</h2><p>El visor consume el CSV o JSON exportado; no entrena modelos al cambiar filtros. Python mantiene el entrenamiento, la validación y el formato oficial. El notebook de Colab ejecuta ese mismo motor. Conserva manifest.json, metrics.json, replicabilidad.csv y la declaración de uso de IA junto con la entrega.</p><p>La evaluación del reto asigna AUC 50%, RMSE log 20%, Winkler log 5%, replicabilidad 5% y panel de finalistas 20%. No se calcula aquí un puntaje combinado sin la normalización oficial.</p></section></div>}
      <footer className="page-footer"><span>TECTON · Hackathon PNUD Colombia</span><span>Unidad: municipio × mes · Resultados de modelo</span></footer>
    </main>
  </div>;
}
